import type {
  TemplateDocumentType,
  TemplateExtension,
  TemplateSource,
} from "./template.types";

export const allowedTemplateExtensions = new Set<TemplateExtension>([
  ".docx",
  ".dotx",
  ".doc",
]);

export const maximumTemplateFileSize = 25 * 1024 * 1024;

export const templateTypeLabels: Record<TemplateDocumentType, string> = {
  anschreiben: "Anschreiben",
  deckblatt: "Deckblatt",
  lebenslauf: "Lebenslauf",
};

export const templateSourceLabels: Record<TemplateSource, string> = {
  "muster-folder": "Musterordner",
  "existing-document": "Eigenes Dokument",
  "uploaded-word-template": "Eigene Word-Vorlage",
  "system-word-template": "System Word-Vorlage",
};

export const defaultTemplateSortOrder = 1_000;

export const wordMusterTemplateConfig = {
  id: "word-muster-anschreiben",
  fileName: "Anschreiben_Muster.docx",
  name: "Word Muster",
  documentType: "anschreiben",
  format: "docx",
  source: "uploaded-word-template",
  sortOrder: 2,
  isSystemTemplate: false,
  supportsPreview: true,
  supportsPlaceholders: true,
  editableInWord: true,
  isProtected: true,
  description:
    "Eigene Word-Vorlage für Anschreiben. Beim Verwenden wird immer eine neue, ausgefüllte Kopie erstellt.",
  tags: ["Word", "DOCX", "Anschreiben"],
} as const;

export const elegantLebenslaufTemplateConfig = {
  id: "word-lebenslauf-elegant",
  fileName: "Elegant_Lebenslauf_Muster.docx",
  atsFileName: "Elegant_Lebenslauf_ATS.docx",
  previewFileName: "Elegant_Lebenslauf_Muster.preview.png",
  name: "Elegant",
  documentType: "lebenslauf",
  format: "docx",
  source: "system-word-template",
  sortOrder: 6,
  category: "elegant",
  layout: "two-column-right-sidebar",
  atsFriendly: true,
  supportsPhoto: true,
  supportsPlaceholders: true,
  supportsPreview: true,
  supportsAtsMode: true,
  editableInWord: true,
  isSystemTemplate: true,
  isProtected: true,
  description:
    "Zweispaltige Word-Lebenslaufvorlage mit breiter Hauptspalte für Berufserfahrung und eleganter roter Seitenleiste für persönliche Highlights.",
  tags: ["Elegant", "Word", "DOCX", "Lebenslauf", "ATS", "Foto"],
  cardHighlights: [
    "Breite Hauptspalte für Berufserfahrung",
    "Rote Seitenleiste für persönliche Highlights",
  ],
} as const;

export const zeitgenoessischLebenslaufTemplateConfig = {
  id: "word-lebenslauf-zeitgenoessisch",
  fileName: "Zeitgenoessisch_Lebenslauf_Muster.docx",
  atsFileName: "Zeitgenoessisch_Lebenslauf_ATS.docx",
  previewFileName: "Zeitgenoessisch_Lebenslauf_Muster.preview.png",
  name: "Zeitgenössisch",
  documentType: "lebenslauf",
  format: "docx",
  source: "system-word-template",
  sortOrder: 3,
  category: "contemporary",
  layout: "two-column-left-sidebar",
  atsFriendly: true,
  supportsPhoto: true,
  supportsPlaceholders: true,
  supportsPreview: true,
  supportsAtsMode: true,
  editableInWord: true,
  isSystemTemplate: true,
  isProtected: true,
  description:
    "Grüne moderne Word-Lebenslaufvorlage. Saubere zweispaltige Struktur mit Foto, Stärken, Zusammenfassung und Erfahrung.",
  tags: [
    "Zeitgenössisch",
    "Word",
    "DOCX",
    "Lebenslauf",
    "ATS",
    "Foto",
    "Grün",
  ],
  cardHighlights: [
    "Grüne moderne Word-Lebenslaufvorlage",
    "Foto, Stärken, Zusammenfassung und Erfahrung",
  ],
} as const;

export const gepflegtLebenslaufTemplateConfig = {
  id: "word-lebenslauf-gepflegt",
  fileName: "Gepflegt_Lebenslauf_Muster.docx",
  atsFileName: "Gepflegt_Lebenslauf_ATS.docx",
  previewFileName: "Gepflegt_Lebenslauf_Muster.preview.png",
  name: "Gepflegt",
  documentType: "lebenslauf",
  format: "docx",
  source: "system-word-template",
  sortOrder: 7,
  category: "business",
  layout: "two-column-left-sidebar",
  atsFriendly: true,
  supportsPhoto: true,
  supportsPlaceholders: true,
  supportsPreview: true,
  supportsAtsMode: true,
  editableInWord: true,
  isSystemTemplate: true,
  isProtected: true,
  description:
    "Raffinierte Business-Lebenslaufvorlage mit linker Farbfläche und klarer Informationshierarchie.",
  tags: [
    "Gepflegt",
    "Word",
    "DOCX",
    "Lebenslauf",
    "ATS",
    "Business",
    "Kundenorientiert",
  ],
  cardHighlights: [
    "Linke Farbfläche für Profil und Kernkompetenzen",
    "Klare Business-Hierarchie für kundenorientierte Rollen",
  ],
} as const;

export const modernLebenslaufTemplateConfig = {
  id: "word-lebenslauf-modern",
  fileName: "Modern_Lebenslauf_Muster.docx",
  atsFileName: "Modern_Lebenslauf_ATS.docx",
  previewFileName: "Modern_Lebenslauf_Muster.preview.png",
  name: "Modern",
  documentType: "lebenslauf",
  format: "docx",
  source: "system-word-template",
  sortOrder: 8,
  category: "creative-professional",
  layout: "two-column-equal",
  atsFriendly: true,
  supportsPhoto: true,
  supportsPlaceholders: true,
  supportsPreview: true,
  supportsAtsMode: true,
  editableInWord: true,
  isSystemTemplate: true,
  isProtected: true,
  description:
    "Perfekte Lebenslauf-Vorlage mit kreativen Elementen, die Berufserfahrung und Qualifikationen übersichtlich zur Geltung bringt.",
  tags: [
    "Modern",
    "Word",
    "DOCX",
    "Lebenslauf",
    "ATS",
    "Türkis",
    "Kreativ",
    "Professionell",
  ],
  cardHighlights: [
    "Türkise Wellenmuster für professionelle Ausstrahlung",
    "Zwei Spalten mit separaten Kontakt- und Erfahrungsbereichen",
  ],
} as const;

export const kreativLebenslaufTemplateConfig = {
  id: "word-lebenslauf-kreativ",
  fileName: "Kreativ_Lebenslauf_Muster.docx",
  atsFileName: "Kreativ_Lebenslauf_ATS.docx",
  previewFileName: "Kreativ_Lebenslauf_Muster.preview.png",
  name: "Kreativ",
  documentType: "lebenslauf",
  format: "docx",
  source: "system-word-template",
  sortOrder: 4,
  category: "creative",
  layout: "two-column-header-banner",
  atsFriendly: true,
  supportsPhoto: true,
  supportsBackground: true,
  supportsPlaceholders: true,
  supportsPreview: true,
  supportsAtsMode: true,
  editableInWord: true,
  isSystemTemplate: true,
  isProtected: true,
  emphasis: "compact-information",
  description:
    "Kompakte, kreative Word-Lebenslaufvorlage. Ideal, um viele Informationen übersichtlich auf einer Seite unterzubringen.",
  tags: [
    "Kreativ",
    "Word",
    "DOCX",
    "Lebenslauf",
    "ATS",
    "Foto",
    "Zweispaltig",
    "Kompakt",
  ],
  colorVariants: {
    gruen: "#39B774",
    schwarz: "#111111",
    dunkelblau: "#244766",
    tuerkis: "#159F9B",
    violett: "#7052B5",
    orange: "#D97706",
  },
  cardHighlights: [
    "Viele Informationen übersichtlich auf einer Seite",
    "Zweispaltig · Mit Foto · DOCX",
  ],
} as const;

export const ivyLeagueLebenslaufTemplateConfig = {
  id: "word-lebenslauf-ivy-league",
  fileName: "Ivy_League_Lebenslauf_Muster.docx",
  atsFileName: "Ivy_League_Lebenslauf_ATS.docx",
  previewFileName: "Ivy_League_Lebenslauf_Muster.preview.png",
  name: "Ivy League",
  documentType: "lebenslauf",
  format: "docx",
  source: "system-word-template",
  sortOrder: 9,
  category: "classic-professional",
  layout: "single-column-watercolor",
  atsFriendly: true,
  supportsPhoto: false,
  supportsBackground: true,
  supportsPlaceholders: true,
  supportsPreview: true,
  supportsAtsMode: true,
  editableInWord: true,
  isSystemTemplate: true,
  isProtected: true,
  emphasis: "classic-single-column",
  description:
    "Die klassische Harvard-Lebenslaufvorlage, aktualisiert für das 21. Jahrhundert mit einem raffinierten, ATS-freundlichen Design.",
  tags: [
    "Ivy League",
    "Word",
    "DOCX",
    "Lebenslauf",
    "ATS",
    "Ohne Foto",
    "Einspaltig",
    "Klassisch",
  ],
  cardHighlights: [
    "Klassische Serifentypografie mit ruhiger Einspaltenstruktur",
    "Pastell-Hintergrund · Ohne Foto · ATS-freundlich",
  ],
} as const;

export const kompaktLebenslaufTemplateConfig = {
  id: "word-lebenslauf-kompakt",
  fileName: "Kompakt_Lebenslauf_Muster.docx",
  atsFileName: "Kompakt_Lebenslauf_ATS.docx",
  previewFileName: "Kompakt_Lebenslauf_Muster.preview.png",
  name: "Kompakt",
  documentType: "lebenslauf",
  format: "docx",
  source: "system-word-template",
  sortOrder: 5,
  category: "compact",
  layout: "two-column-compact",
  atsFriendly: true,
  supportsPhoto: false,
  supportsBackground: true,
  supportsPlaceholders: true,
  supportsPreview: true,
  supportsAtsMode: true,
  editableInWord: true,
  isSystemTemplate: true,
  isProtected: true,
  emphasis: "single-page-high-density",
  description:
    "Einseitige Word-Lebenslaufvorlage mit kleineren Seitenrändern und hoher Informationsdichte.",
  tags: [
    "Kompakt",
    "Word",
    "DOCX",
    "Lebenslauf",
    "ATS",
    "Ohne Foto",
    "Zweispaltig",
    "Einseitig",
  ],
  colorVariants: {
    dunkelblau: "#0A3485",
    schwarz: "#111111",
    petrol: "#145B63",
    violett: "#5B3F91",
    dunkelgruen: "#185D47",
  },
  cardHighlights: [
    "Einseitig · Hohe Informationsdichte",
    "Zweispaltig · Ohne Foto · ATS-freundlich · DOCX",
  ],
} as const;

export const stilvollLebenslaufTemplateConfig = {
  id: "word-lebenslauf-stilvoll",
  fileName: "Stilvoll_Lebenslauf_Muster.docx",
  atsFileName: "Stilvoll_Lebenslauf_ATS.docx",
  previewFileName: "Stilvoll_Lebenslauf_Muster.preview.png",
  name: "Stilvoll",
  documentType: "lebenslauf",
  format: "docx",
  source: "system-word-template",
  sortOrder: 10,
  category: "modern-professional",
  layout: "two-column-right-wide",
  atsFriendly: true,
  supportsPhoto: true,
  supportsBackground: true,
  supportsPlaceholders: true,
  supportsPreview: true,
  supportsAtsMode: true,
  editableInWord: true,
  isSystemTemplate: true,
  isProtected: true,
  emphasis: "skills-and-career",
  description:
    "Stilvolle Word-Lebenslaufvorlage mit kompakter linker Informationsspalte, breiter Karrierespalte und geometrischem Hintergrund.",
  tags: [
    "Stilvoll",
    "Word",
    "DOCX",
    "Lebenslauf",
    "ATS",
    "Foto",
    "Zweispaltig",
    "Grün",
  ],
  cardHighlights: [
    "Kompakte Profilspalte und breite Karrierespalte",
    "Geometrisches Muster · Mit Foto · ATS-freundlich",
  ],
} as const;

export const einfachLebenslaufTemplateConfig = {
  id: "word-lebenslauf-einfach",
  fileName: "Einfach_Lebenslauf_Muster.docx",
  atsFileName: "Einfach_Lebenslauf_ATS.docx",
  previewFileName: "Einfach_Lebenslauf_Muster.preview.png",
  name: "Einfach",
  documentType: "lebenslauf",
  format: "docx",
  source: "system-word-template",
  sortOrder: 11,
  category: "simple-professional",
  layout: "single-column",
  atsFriendly: true,
  supportsPhoto: true,
  supportsBackground: true,
  supportsPlaceholders: true,
  supportsPreview: true,
  supportsAtsMode: true,
  editableInWord: true,
  isSystemTemplate: true,
  isProtected: true,
  emphasis: "simple-ats",
  description:
    "Einfache einspaltige Word-Lebenslaufvorlage mit klarer blauer Hierarchie und separater ATS-Ausgabe.",
  tags: [
    "Einfach",
    "Word",
    "DOCX",
    "Lebenslauf",
    "ATS",
    "Foto",
    "Einspaltig",
    "Blau",
  ],
  cardHighlights: [
    "Klare Einspaltenstruktur mit kräftigen Abschnittslinien",
    "Mit Foto · Geometrisches Dekor · ATS-freundlich",
  ],
} as const;

const coreTemplatePlaceholderKeys = [
  "BEWERBER_NAME",
  "BEWERBER_VORNAME",
  "BEWERBER_NACHNAME",
  "BEWERBER_ADRESSE",
  "BEWERBER_PLZ",
  "BEWERBER_ORT",
  "BEWERBER_TELEFON",
  "BEWERBER_EMAIL",
  "FIRMA_NAME",
  "FIRMA_ADRESSE",
  "FIRMA_PLZ",
  "FIRMA_ORT",
  "ANSPRECHPARTNER",
  "STELLENBEZEICHNUNG",
  "STELLENNUMMER",
  "BEWERBUNGSDATUM",
  "BETREFF",
  "ANREDE",
  "EINLEITUNG",
  "HAUPTTEXT",
  "SCHLUSSTEXT",
  "GRUSSFORMEL",
  "UNTERSCHRIFT",
  "KENNTNISSE",
] as const;

export type TemplatePlaceholderKey =
  (typeof coreTemplatePlaceholderKeys)[number];

export const templatePlaceholderAliases = {
  FIRMA_ADI: "FIRMA_NAME",
  FIRMA_ADRESI: "FIRMA_ADRESSE",
  POSTA_KODU: "FIRMA_PLZ",
  SEHIR: "FIRMA_ORT",
  TARIH: "BEWERBUNGSDATUM",
  STELLE: "STELLENBEZEICHNUNG",
  REFERENZNUMMER: "STELLENNUMMER",
  ANSCHREIBEN_METNI: "HAUPTTEXT",
  KAPANIS: "SCHLUSSTEXT",
} as const satisfies Record<string, TemplatePlaceholderKey>;

const elegantStaticPlaceholderKeys = [
  "VORNAME",
  "NACHNAME",
  "BERUFSBEZEICHNUNG",
  "FACHGEBIET_1",
  "FACHGEBIET_2",
  "FACHGEBIETE",
  "TELEFON",
  "EMAIL",
  "WEBSITE",
  "LINKEDIN",
  "ORT",
  "GEBURTSDATUM",
  "GEBURTSORT",
  "GEBURTSZEILE",
  "GITHUB",
  "KONTAKTDATEN_TITEL",
  "KONTAKT_ZEILE_1",
  "KONTAKT_ZEILE_2",
  "KONTAKT_ZEILE_3",
  "KONTAKTE_TITEL",
  "HEADER_KONTAKT_1",
  "HEADER_KONTAKT_2",
  "HEADER_KONTAKT_3",
  "HEADER_KONTAKT_4",
  "HEADER_KONTAKT_5",
  "HEADER_KONTAKT_6",
  "TELEFON_ZEILE",
  "EMAIL_ZEILE",
  "WEBSITE_ZEILE",
  "LINKEDIN_ZEILE",
  "ORT_ZEILE",
  "PROFILFOTO",
  "ZUSAMMENFASSUNG_TITEL",
  "ZUSAMMENFASSUNG",
  "STAERKEN_TITEL",
  "STAERKEN_ATS",
  "ERFOLGE_TITEL",
  "ERFOLGE_ATS",
  "ERFOLG_HIGHLIGHT_1_TITEL",
  "ERFOLG_HIGHLIGHT_1_BESCHREIBUNG",
  "ERFOLG_HIGHLIGHT_2_TITEL",
  "ERFOLG_HIGHLIGHT_2_BESCHREIBUNG",
  "KENNTNISSE_TITEL",
  "SPRACHEN_TITEL",
  "SPRACHEN_ATS",
  "BERUFSERFAHRUNG_TITEL",
  "ERFAHRUNG_TITEL",
  "AUSBILDUNG_TITEL",
  "PROJEKTE_TITEL",
  "PROJEKTE",
  "WEITERBILDUNGEN_TITEL",
  "WEITERBILDUNGEN",
  "ZERTIFIKATE_TITEL",
  "ZERTIFIKATE",
  "VEROEFFENTLICHUNGEN_TITEL",
  "VEROEFFENTLICHUNGEN",
  "EHRENAMT_TITEL",
  "EHRENAMT",
  "SOFTWARE_TITEL",
  "SOFTWARE",
  "ZUSATZANGABEN_TITEL",
  "ZUSATZANGABEN",
  "FUEHRERSCHEIN_TITEL",
  "FUEHRERSCHEIN",
  "INTERESSEN_TITEL",
  "INTERESSEN",
  "ATS_MODUS",
] as const;

const numberedPlaceholderKeys = (
  count: number,
  fields: readonly string[],
) =>
  Array.from({ length: count }, (_, offset) =>
    fields.map((field) => `${field}_${offset + 1}`),
  ).flat();

export const elegantTemplatePlaceholderKeys: readonly string[] = [
  ...elegantStaticPlaceholderKeys,
  ...numberedPlaceholderKeys(8, [
    "POSITION",
    "UNTERNEHMEN",
    "STARTDATUM",
    "DATUM_TRENNER",
    "ENDDATUM",
    "ARBEITSORT",
    "BESCHREIBUNG",
    "METADATA_TRENNER",
    "TECHNOLOGIEN",
    "ERFAHRUNG_TRENNER",
  ]),
  ...Array.from({ length: 8 }, (_, experienceOffset) =>
    Array.from(
      { length: 5 },
      (_, achievementOffset) =>
        `ERFOLG_${experienceOffset + 1}_${achievementOffset + 1}`,
    ),
  ).flat(),
  ...numberedPlaceholderKeys(3, [
    "ABSCHLUSS",
    "FACHRICHTUNG",
    "HOCHSCHULE",
    "AUSBILDUNG_START",
    "AUSBILDUNG_DATUM_TRENNER",
    "AUSBILDUNG_ENDE",
    "AUSBILDUNG_ORT",
    "AUSBILDUNG_METADATA_TRENNER",
  ]),
  ...numberedPlaceholderKeys(3, ["SPRACHE", "SPRACHNIVEAU"]),
  ...Array.from(
    { length: 3 },
    (_, offset) => `SPRACHE_${offset + 1}_PUNKTE`,
  ),
  ...Array.from({ length: 4 }, (_, offset) => [
    `STAERKE_${offset + 1}_TITEL`,
    `STAERKE_${offset + 1}_BESCHREIBUNG`,
  ]).flat(),
  ...numberedPlaceholderKeys(6, [
    "KENNTNIS_KATEGORIE",
    "KENNTNIS_EINTRAEGE",
  ]),
];

export const templatePlaceholderKeys: readonly string[] = [
  ...coreTemplatePlaceholderKeys,
  ...elegantTemplatePlaceholderKeys,
];
